//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenProAgro.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_ESTADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_ESTADO()
        {
            this.CAT_GEORREFERENCIAS = new HashSet<CAT_GEORREFERENCIAS>();
            this.CAT_USUARIO_ESTADO = new HashSet<CAT_USUARIO_ESTADO>();
        }
    
        public int idEstado { get; set; }
        public string NombreEstado { get; set; }
        public string Abreviatura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_GEORREFERENCIAS> CAT_GEORREFERENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_USUARIO_ESTADO> CAT_USUARIO_ESTADO { get; set; }
    }
}
