//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenProAgro.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_GEORREFERENCIAS
    {
        public int idGeorreferencia { get; set; }
        public Nullable<int> idEstado { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
    
        public virtual CAT_ESTADO CAT_ESTADO { get; set; }
    }
}
